#!/bin/bash

ORIGINAL_VENDOR_STRING="com_irontec"
ORIGINAL_ZIMLET_SUBSTRING="zsugar"
ORIGINAL_ZIMLET_STRING="${ORIGINAL_VENDOR_STRING}_${ORIGINAL_ZIMLET_SUBSTRING}"
VENDOR_STRING="com_btactic"
ZIMLET_SUBSTRING="bsugar"
ZIMLET_STRING="${VENDOR_STRING}_${ZIMLET_SUBSTRING}"
